# Generated by Django 4.1.2 on 2023-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/bestFilm')),
                ('film_type', models.CharField(max_length=300)),
                ('views', models.IntegerField(max_length=20)),
                ('comments', models.IntegerField(max_length=20)),
            ],
        ),
    ]
